### PR TITLE
Redis: Fix compatibility with `node-redis` v4

### PR DESCRIPTION
**Pull request by pipe1404**
`node-redis` v4 has made some breaking changes (vs v3). 
Please see [this](https://github.com/redis/node-redis/blob/master/docs/v3-to-v4.md). So, I have updated `setup` method and added a property in README. 
Can you review this change? Thank you.

### CODE REVIEW

**Comment by jhuckaby** [comment]
Thank you for your PR.

Note that the new `connect()` method is async, so we'll have to await it, and convert the outer function to async.

**Comment by jhuckaby** [comment]
Wait... never mind... I think... Since we're listening for the `connect` event, and firing the callback in that event handler, I guess this all works itself out, and we don't need an async/await on connect.

Please give me some time to test this before merging.

**Comment by jhuckaby** [comment]
So, I've redesigned the Redis storage engine to the [ioredis](https://www.npmjs.com/package/ioredis) package from NPM.  It is much, much better than node-redis, and I am already using it for the RedisCluster storage engine.  I always intended to standardize both engines on ioredis, I just didn't have the time.

This is a drop-in replacement.  All you should need to do on your end is `npm install ioredis` and everything should just work.

**Comment by pipe1404** [comment]
Haha I'm trying to use Redis as storage for Cronicle and ran into some
problems.

The newer `node-redis` currently has problem with return type of get/put (I
have ran test with my docker Redis and some serialization tests failed). I
don't have much time to resolve this but thanks for letting me know that.

Thank you.

**Comment by jhuckaby** [comment]
Hmm, I've never tested Cronicle with a Redis backend, and it is not currently supported.  Your mileage may vary.

**Pull request closed without merging**
